config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  resources :sms_sends do
    get 'sms_sends/new_all', to: 'sms_sends#new_all', on: :collection
    post 'sms_sends', to: 'sms_sends#create_all', on: :collection
  end
  root 'contacts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :first_name, :last_name, :phonenumber, presence: true
  validates :phonenumber, length: { maximum: 12 , minimum: 12}
  validates_numericality_of :phonenumber
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = current_user.contacts
  end
  def new
    @contact = Contact.new
  end
  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      redirect_to contacts_path
    else
      render 'new'
    end
  end
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to contacts_path
  end

  private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phonenumber)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/index.html.erb
<%= flash[:success] %><br>
<%= link_to('Logout', destroy_user_session_path, method: :delete) %>
<h1>All Contacts</h1>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone Number</th>
      <th>Send Message</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.first_name %></td>
      <td><%= contact.last_name %></td>
      <td><%= contact.phonenumber %></td>
      <td><%= link_to 'sms', new_sms_send_path(id: contact.id)%></td>
      <td><%= link_to 'delete', contact_path(contact), method: :delete, data: {confirm: 'Are you like 100% sure?' }%></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <br>
  <%= link_to 'New Contact', new_contact_path %>
  <%= link_to 'Message All your Contacts', sms_sends_new_all_sms_sends_path %>

app/views/contacts/new.html.erb
<%= form_for @contact, url: {action: "create"} do |f|%>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this Contact from being saved:</h2>

      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  First Name: <%= f.text_field :first_name%>
Last Name:  <%= f.text_field :last_name%>
 Phone Number: <%= f.text_field :phonenumber%>
  <%= f.submit "create" %>
<% end %>